import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel, Field

# ── Config ─────────────────────────────────────────────────────────────────────

BOOTSTRAP_SECRET     = os.environ["BOOTSTRAP_SECRET"]
GITHUB_TOKEN         = os.environ["GITHUB_TOKEN"]
GITHUB_DEFAULT_OWNER = os.environ["GITHUB_DEFAULT_OWNER"]
RAILWAY_API_TOKEN    = os.environ["RAILWAY_API_TOKEN"]

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

TEMPLATE_MAP = {
    "python-web":    TEMPLATES_DIR / "python-web-template",
    "python-task":   TEMPLATES_DIR / "python-task-template",
    "telegram-bot":  TEMPLATES_DIR / "telegram-bot-template",
}

# ── Schemas ────────────────────────────────────────────────────────────────────

class CreateAppRequest(BaseModel):
    name: str
    template: str
    product_spec: str
    technical_notes: str = ""
    env_vars: dict[str, str] = Field(default_factory=dict)

class CreateAppResponse(BaseModel):
    repo_url: str
    live_url: str
    deploy_status: str
    github_repo_name: str

# ── Helpers ────────────────────────────────────────────────────────────────────

def run(args: list[str], cwd: str | None = None, extra_env: dict | None = None) -> str:
    env = {**os.environ, **(extra_env or {})}
    return subprocess.run(args, capture_output=True, text=True, env=env, check=True, cwd=cwd).stdout.strip()

def auth_clone_url(repo_full_name: str) -> str:
    return f"https://x-access-token:{GITHUB_TOKEN}@github.com/{repo_full_name}.git"

# ── GitHub ─────────────────────────────────────────────────────────────────────

def create_github_repo(name: str) -> dict:
    full_name = f"{GITHUB_DEFAULT_OWNER}/{name}"
    run(["gh", "repo", "create", full_name, "--private"],
        extra_env={"GH_TOKEN": GITHUB_TOKEN})
    return {"full_name": full_name, "html_url": f"https://github.com/{full_name}"}

def bootstrap_repo(repo_full_name: str, template: str, generated_files: dict[str, str]) -> None:
    code_template = TEMPLATE_MAP[template]
    repo_template = TEMPLATES_DIR / "github-repo-template"
    git_env = {"GIT_AUTHOR_NAME": "bootstrap", "GIT_AUTHOR_EMAIL": "bootstrap@local",
               "GIT_COMMITTER_NAME": "bootstrap", "GIT_COMMITTER_EMAIL": "bootstrap@local"}

    with tempfile.TemporaryDirectory() as d:
        # Copy doc template then code template (code files win on conflict)
        shutil.copytree(str(repo_template), d, dirs_exist_ok=True)
        shutil.copytree(str(code_template), d, dirs_exist_ok=True)

        # Overwrite with generated content
        for path, content in generated_files.items():
            dest = Path(d) / path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content)

        # Init, commit, push
        run(["git", "init"], cwd=d, extra_env=git_env)
        run(["git", "symbolic-ref", "HEAD", "refs/heads/main"], cwd=d)
        run(["git", "remote", "add", "origin", auth_clone_url(repo_full_name)], cwd=d)
        run(["git", "add", "."], cwd=d, extra_env=git_env)
        run(["git", "commit", "-m", "Bootstrap initial files"], cwd=d, extra_env=git_env)
        run(["git", "push", "-u", "origin", "main"], cwd=d, extra_env=git_env)

# ── Railway ────────────────────────────────────────────────────────────────────

def provision_railway(repo_full_name: str, app_name: str, env_vars: dict[str, str]) -> dict:
    renv = {"RAILWAY_TOKEN": RAILWAY_API_TOKEN}
    with tempfile.TemporaryDirectory() as d:
        run(["git", "clone", auth_clone_url(repo_full_name), d])
        run(["railway", "project", "create", "--name", app_name], cwd=d, extra_env=renv)
        for key, value in env_vars.items():
            run(["railway", "variables", "--set", f"{key}={value}"], cwd=d, extra_env=renv)
        run(["railway", "up", "--detach"], cwd=d, extra_env=renv)
        run(["railway", "domain"], cwd=d, extra_env=renv)
    # NOTE: one-time manual step — connect GitHub repo for auto-redeploy:
    #   Railway dashboard → Service → Settings → Source → GitHub → repo → branch main
    return {"live_url": f"https://{app_name}.up.railway.app", "deploy_status": "deploying"}

# ── Generators ─────────────────────────────────────────────────────────────────

def make_readme(name: str, product_spec: str) -> str:
    return f"# {name}\n\n{product_spec}\n"

def make_implementation(name: str, notes: str) -> str:
    return f"""# Implementation Spec

Generated by bootstrap. Fill in sections as you build.

## Stack

- Python / Railway
{notes and f'- {notes}' or ''}

## Agent

[Define agent flows here.]

## Data

[Define schemas here.]

## Auth

[Define auth model here.]

## Security

- Secrets in Railway env vars
- Repo is private by default
"""

# ── App ────────────────────────────────────────────────────────────────────────

app = FastAPI(title="Bootstrap Factory")

@app.get("/healthz")
def healthz() -> dict:
    return {"status": "ok"}

@app.post("/create-app", response_model=CreateAppResponse)
def create_app(payload: CreateAppRequest, authorization: str | None = Header(default=None)):
    if authorization != f"Bearer {BOOTSTRAP_SECRET}":
        raise HTTPException(status_code=401, detail="Unauthorized")
    if payload.template not in TEMPLATE_MAP:
        raise HTTPException(status_code=400, detail=f"Unknown template. Choose from: {list(TEMPLATE_MAP)}")

    repo = create_github_repo(payload.name)
    bootstrap_repo(
        repo_full_name=repo["full_name"],
        template=payload.template,
        generated_files={
            "README.md":        make_readme(payload.name, payload.product_spec),
            "IMPLEMENTATION.md": make_implementation(payload.name, payload.technical_notes),
        },
    )
    railway = provision_railway(repo["full_name"], payload.name, payload.env_vars)

    return CreateAppResponse(
        repo_url=repo["html_url"],
        live_url=railway["live_url"],
        deploy_status=railway["deploy_status"],
        github_repo_name=repo["full_name"],
    )
